name: Evolene CI

on:  
  push:
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
          - '*.md'
          - '*.png'
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        env:
          SLACK_CHANNELS: "#team-pipeline-build"
          NPM_UPDATES_AVAILABLE: True
          BUILD_INFORMATION_OUTPUT_FILE: "/config/version.js"
        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}

